name: desenho

services:
  excalidraw:
    image: ghcr.io/ivancarlosti/fitdraw:latest
    container_name: desenho-frontend
    ports:
      - "3030:80"
    environment:
      - VITE_APP_WS_SERVER_URL=https://fitdraw.example.com
      - VITE_APP_PLUS_APP_URL=false
    restart: unless-stopped
    entrypoint: /bin/sh
    command: >
      -c "echo 'Patching WebSocket URL...' &&
          find /usr/share/nginx/html/ -type f -name '*.js' -exec sed -i \"s|https://oss-collab.excalidraw.com|$${VITE_APP_WS_SERVER_URL}|g\" {} + &&
          nginx -g 'daemon off;'"

  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    container_name: desenho-backend
    ports:
      - "8082:80"
    restart: unless-stopped
